name: Polaris SCA Scan

on:
  push:
    branches:
      - feature
  workflow_dispatch:

jobs:
  polaris-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Download Bridge CLI
        run: |
          curl -L -o bridge.zip "$BRIDGE_DOWNLOAD_URL"
          unzip bridge.zip -d bridge

      - name: Run Polaris SCA Scan
        env:
          POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          BRIDGE_DOWNLOAD_URL: ${{ secrets.BRIDGE_DOWNLOAD_URL }}
        run: |
          chmod +x bridge/bridge-cli*

          bridge/bridge-cli \
            --stage polaris \
            polaris.project.name="test-php" \
            polaris.branch.name="feature" \
            polaris.application.name="harika-test-polaris" \
            polaris.serverUrl="https://poc.polaris.blackduck.com/" \
            polaris.assessment.types="SCA" \
            polaris.test.sca.type="SCA-PACKAGE"
